- name: Instalacja tmux na WSL
  hosts: localhost
  connection: local
  become: yes
  become_method: sudo

  tasks:
    - name: Install tmux
      package:
        name: tmux
        state: present
      tags: tmux