---
- name: Setup configuration File
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
  - name: Create symbolic link /home/m/files/.tmux.conf -> /home/m
    file:
      src: /home/m/files/.tmux.conf
      dest: /home/m/.tmux.conf
      state: link
      force: yes
      owner: m
