---
- name: Setup configuration File
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
  - name: Create symbolic link $HOME/files/.tmux.conf -> $HOME
    file:
      src: $HOME/files/.tmux.conf
      dest: $HOME/.tmux.conf
      state: link
      force: yes
      owner: m
