---
- name: Setup tmux repo envirement
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
  - name: Clone Config repo into files folder
    get_url:
      url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
      dest: "$HOME/install.sh"
      mode: '0755'

  - name: Install Oh-My-ZSH skrypt
    script:
      cmd: "/home/m/install.sh --unattended"

  - name: Set user shell to zsh
    user:
      name: "m"
      shell: /bin/zsh
    become: true

  - name: Clone zsh-autosuggestions repo into plugins folder
    git: 
      repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
      dest: "$HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions/"


  - name: Clone zsh-syntax-highlighting repo into plugins folder
    git:
      repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
      dest: "$HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"

  - name: Clone zsh-completions repo into plugins folder
    git:
      repo: "https://github.com/zsh-users/zsh-completions"
      dest: "$HOME/.oh-my-zsh/custom/plugins/zsh-completions"

  - name: Clone zsh-docker repo into plugins folder
    git:
      repo: "https://github.com/zsh-users/zsh-docker.git"
      dest: "$HOME/.oh-my-zsh/custom/plugins/zsh-docker"

  - name: Clone auto-color-ls repo into plugins folder
    git:
      repo: "https://github.com/gretzky/auto-color-ls.git"
      dest: "$HOME/.oh-my-zsh/custom/plugins/auto-color-ls"

  - name: Clone common.zsh-theme repo into plugins themes
    get_url:
      url: "https://raw.githubusercontent.com/jackharrisonsherlock/common/refs/heads/master/common.zsh-theme"
      dest: "$HOME/.oh-my-zsh/custom/themes/common.zsh-theme"